"""
Django settings for proj project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import kdb
from pathlib import Path


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1s1nfv59%b(rs2jy_+xod8w@t=l9pu$-ex^@ef*x@p6l=udszj'


# Configure via LibElektra
with kdb.KDB() as k:
    ks = kdb.KeySet()
    k.get(ks, 'user:/sw/django/#0/current')
    database_count = ks['user:/sw/django/#0/current/databases'].getMeta('array').value

    DEBUG = True if ks['/sw/django/#0/current/debug'].get() else False
    ALLOWED_HOSTS = [x.value for x in ks if '/sw/django/#0/current/allowed_hosts/' in x.name]
    CSRF_TRUSTED_ORIGINS = [x.value for x in ks if '/sw/django/#0/current/csrf_origins/' in x.name]

    DATABASES = {
        x.value: {
            'ENGINE': ks[f"{x}/engine"].value,
            'NAME': ks[f"{x}/name"].value,
            'USER': ks[f"{x}/user"].value,
            'PASSWORD': ks[f"{x}/password"].value,
            'PORT': ks[f"{x}/port"].value,
        } for x in ks if '/sw/django/#0/current/databases/' in x.name and len(x) == 7
    }

    INSTALLED_APPS = [x.value for x in ks if '/sw/django/#0/current/apps/' in x.name]

# Application definition

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "proj.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "proj.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"
