name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test_spec:
    runs-on: ubuntu-latest
    container:
      image: elektra/elektra:0.9.9-6-bullseye
      options: -u root
    steps:
      - uses: actions/checkout@v3
      - run: "${GITHUB_WORKSPACE}/spec/create-spec.sh"
      - run: "${GITHUB_WORKSPACE}/spec/test-spec.sh"

  test_django:
    runs-on: ubuntu-latest
    container:
      image: elektra/elektra:0.9.9-6-bullseye
      options: -u root
    steps:
      - uses: actions/checkout@v3
      - run: "apt update"
      - run: "apt install -y python3-venv"
      - run: "python3 -m venv venv --system-site-packages"
      - run: "./venv/bin/pip install -r requirements.txt"
      - run: "${GITHUB_WORKSPACE}/spec/test-spec.sh"
      - run: "./venv/bin/python3 manage.py migrate"
